USE MundoPokemon_DB;
GO

SELECT *
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';


USE MundoPokemon_DB;
GO

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'NOMBRE_DE_LA_TABLA';


SELECT 
    t.TABLE_NAME AS 'Tabla',
    c.COLUMN_NAME AS 'Columna',
    c.DATA_TYPE AS 'Tipo de Datos',
    c.CHARACTER_MAXIMUM_LENGTH AS 'Longitud Máxima',
    c.IS_NULLABLE AS 'Es Nullable'
FROM 
    INFORMATION_SCHEMA.TABLES t
JOIN 
    INFORMATION_SCHEMA.COLUMNS c ON t.TABLE_NAME = c.TABLE_NAME
WHERE 
    t.TABLE_TYPE = 'BASE TABLE'
ORDER BY 
    t.TABLE_NAME, 
    c.ORDINAL_POSITION;
