USE [master]
GO

/****** Object:  Database [MVP_IMPRENTA]    Script Date: 21/9/2024 01:20:27 ******/
CREATE DATABASE [MVP_IMPRENTA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MVP_IMPRENTA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MVP_IMPRENTA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MVP_IMPRENTA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MVP_IMPRENTA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MVP_IMPRENTA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MVP_IMPRENTA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET ARITHABORT OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MVP_IMPRENTA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MVP_IMPRENTA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MVP_IMPRENTA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MVP_IMPRENTA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MVP_IMPRENTA] SET  MULTI_USER 
GO

ALTER DATABASE [MVP_IMPRENTA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MVP_IMPRENTA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MVP_IMPRENTA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MVP_IMPRENTA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MVP_IMPRENTA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MVP_IMPRENTA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MVP_IMPRENTA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MVP_IMPRENTA] SET  READ_WRITE 
GO


